title: Samuele Bortolotti's personal web page
author: Samuele Bortolotti
email: samuele.bortolotti@studenti.unitn.it
description: >- # this means to ignore newlines until "baseurl:"
  Samuele Bortolotti's personal web page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://samuelebortolotti.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: samuelebortolotti
repository: samuelebortolotti/samuelebortolotti.github.io 

# Use MathJax
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Build settings
encoding: UTF-8
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag

# Default language
include: [en]

# Projects and Publications collection
collections:
  projects:
    output: true
    permalink: /:lang/projects/:title
  publications:
    output: true
    permalink: /publications/:title
  

feed:
  posts_limit: 20
  collections:
    - projects
    - publications

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor