#!/usr/bin/env ruby
# frozen_string_literal: true

# ---------------------------------------------------------------------------
# gen_bib.rb
#
# Collects the BibTeX blocks from `_publications/*.md` (the fenced code block
# under "## How to cite") into a single .bib file, so the LaTeX CV and the
# website cite the same source.
#
#   ruby scripts/gen_bib.rb [--out PATH] [--check]
#
#   --out PATH   where to write the .bib   (default: cv/resume/references.bib)
#   --check      don't write; exit 2 if the file on disk is out of date
#
# Exit codes: 0 ok / 2 out-of-date (with --check) / 1 error.
# ---------------------------------------------------------------------------

require "optparse"

ROOT     = File.expand_path("..", __dir__)
PUB_DIR  = File.join(ROOT, "_publications")

opts = { out: File.join(ROOT, "cv", "resume", "references.bib"), check: false }
OptionParser.new do |o|
  o.on("--out PATH") { |v| opts[:out] = File.expand_path(v) }
  o.on("--check")    { opts[:check] = true }
end.parse!

# Pull the first ``` ... ``` fence that looks like BibTeX out of a markdown file.
def extract_bibtex(path)
  body = File.read(path)
  body.scan(/```[a-z]*\n(.*?)\n```/m).each do |(block)|
    return block.strip if block =~ /\A\s*@\w+\s*\{/
  end
  nil
end

def cite_key(entry)
  entry[/\A\s*@\w+\s*\{\s*([^,\s]+)/, 1]
end

entries = Dir[File.join(PUB_DIR, "*.md")].sort.filter_map do |path|
  bib = extract_bibtex(path)
  warn "WARN: no BibTeX block in #{File.basename(path)}" unless bib
  bib
end

if entries.empty?
  warn "ERROR: found no BibTeX blocks under _publications/"
  exit 1
end

# newest first, by the 4-digit year in the key when present
entries.sort_by! { |e| [-(cite_key(e).to_s[/\d{4}/].to_i), cite_key(e).to_s] }

header = <<~TXT
  % Generated by scripts/gen_bib.rb from _publications/*.md - do not edit by hand.
  % Regenerate with:  rake cv:bib   (or  ruby scripts/gen_bib.rb)
TXT
rendered = header + "\n" + entries.join("\n\n") + "\n"

if opts[:check]
  current = File.exist?(opts[:out]) ? File.read(opts[:out]) : ""
  if current == rendered
    puts "up to date: #{opts[:out].sub(ROOT + '/', '')}"
    exit 0
  end
  warn "OUT OF DATE: #{opts[:out].sub(ROOT + '/', '')} - run `rake cv:bib`"
  exit 2
end

require "fileutils"
FileUtils.mkdir_p(File.dirname(opts[:out]))
File.write(opts[:out], rendered)
puts "wrote #{opts[:out].sub(ROOT + '/', '')}  (#{entries.size} entries)"
